# VAMOS UTILIZAR ESSE ARQUIVO PARA SIMULAR AS PRIMEIRAS MUDANÇAS NO GITHUB PARA FINS DE TESTE

# ENTÃO PRIMEIRAMENTE:

# ACESSAR O REPOSITÓRIO PRINCIPAL, QUE ESTÁ COMPARTILHADO E CLICAR EM CODE;

# EM SEGUIDA, CLICAR "OPEN WITH GITHUB DESKTOP" OU DOWNLOAD.ZIP;

# A OPÇÃO COM O GITHUB DESKTOP SÓ FUNCIONARÁ SE ESSE APLICATIVO ESTIVER INSTALADO;

## GITHUB DESKTOP: ELE ABRIRÁ E SOLICITARÁ UM LOCAL PARA ESTOCAR OS ARQUIVOS DO PROJETO;

# A OPÇÃO COM DOWNLOAD.ZIP EXIGIRÁ QUE VC EXTRAIA OS ARQUIVOS DENTRO DE UMA PASTA RESERVADA PARA O PROJETO;

## À PARTIR DAÍ, SERÁ NECESSÁRIO ABRIR O PROMPT DE COMANDO OU TERMINAL DO GIT BASH;

## APÓS FAZER AS CONFIGURAÇÕES INICIAIS (GIT CONFIG) SERÁ NECESSÁRIO INDICAR A PASTA DO PROJETO;

## AÍ UMA VEZ INDICADO O LOCAL, EXECUTAR O $ git init PARA O PROGRAMA INSTALAR OS ARQUIVOS GIT NA PASTA;
